### ISSUE TITLE
Wrong using: OpenApi

### ISSUE THREAD

**Issue by MarGraz** [aspnet/AspNetCore.Docs.it-it#35]
Hi,

I'm trying to following this guide, but at this point: https://docs.microsoft.com/it-it/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio#add-and-configure-swagger-middleware you suggest to add a reference to "OpenApi", but isn't possible, because "Swashbuckle" doesn't use "OpenApi". 
The correct using is: "Swashbuckle.AspNetCore.Swagger.Info".

Thank you,
Marco

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Introduzione a Swashbuckle e ad ASP.NET Core](https://docs.microsoft.com/it-it/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio#add-and-configure-swagger-middleware)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by lichasu** [comment]
Hello, @MarGraz ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/13266.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
