### ISSUE TITLE
Accept TodoItem Id from query string

### ISSUE THREAD

**Issue by belfed** [aspnet/AspNetCore.Docs.it-it#44]
Hello,
I'm really new to ASP.NET (Core and Standard) and I came accross this guide, that is what I was looking for. I wanted to ask this: what if, using the same API, I'd want client applications to get a TodoItem with the Id passed as a query string parameter?
This is what I mean: 
`http://localhost:5000/api/TodoItems?Id=1`

I searched for explainations about this and everything I found isn't working. I tried with [FromQuery] attribute, changing the HttpGet content, using Route attribute, nothing is working. Can you please explain how can I achieve this?

Thank you very much for the help.

**Comment by srvbpigh** [comment]
Hello, @belfed
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @belfed, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/16309. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
